var black       = '#000000';
var red         = '#E54B4B';
var green       = '#9ECE58';
var yellow      = '#FAED70';
var blue        = '#396FE2';
var magenta     = '#BB80B3';
var cyan        = '#2DDAFD';
var white       = '#d0d0d0';
var lightBlack  = 'rgba(255, 255, 255, 0.2)';
var lightRed    = '#FF5370';
var lightGreen  = '#C3E88D';
var lightYellow = '#FFCB6B';
var lightBlue   = '#82AAFF';
var lightMagenta= '#C792EA';
var lightCyan   = '#89DDFF';
var lightWhite  = '#ffffff';
term_set('color-palette-overrides',[black, red, green, yellow, blue, magenta, cyan, white, lightBlack, lightRed, lightGreen, lightYellow, lightBlue, lightMagenta, lightCyan, lightWhite]);
term_set('cursor-color', '#FFCC00');
term_set('cursor-blink', true);
term_set('foreground-color', '#ECEFF1');
term_set('background-color', 'rgba(38, 50, 56, 1)');
